name: 'pull-request-update'
description: 'An simple action to process basic updates on the pull request'
inputs:
  token:
    description: 'The repository authentication token'
    required: true
  removeLabel:
    description: 'The label to remove'
    required: false
  addLabel:
    description: 'The label to add'
    required: false 
  assign:
    description: 'The collaborator login to unassign'
    required: false
  unassign:
    description: 'The collaborator login to assign'
    required: false
runs:
  using: 'node12'
  main: 'index.js'