name: 'approve-pull-request'
description: 'Decide if the pull request is approved or not'
inputs:
  token:
    description: 'The repository authentication token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'