name: Creates an empty pull request from an issue

on:
  project_card:
    types: [moved]

jobs:
  update_label: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Github Actions
      uses: actions/checkout@v2

    - name: Install required NPM dependencies
      run: |
        npm i @actions/core 
        npm i @actions/github
        npm i md-2-json
    - name: Create a pull request from the issue
      uses: ./.github/actions/create_pull_request_from_issue/ 
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    