name: Process the issue workflow

on:
  project_card:
    types: [moved]

jobs:
  update_label: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Github Actions
      uses: actions/checkout@v2

    - name: Install required NPM dependencies
      run: |
        npm install @actions/core 
        npm install @actions/github

    - name: Create the pull request
      uses: ./.github/actions/issue_create_pull_request/ 
      run: |
        echo ${{ secrets }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        triggerColumn: InProgress
    
 