name: Request the reviewers

on:
  pull_request:
    types: [ labeled, ready_for_review ]

jobs:    
  # --------------------------------------------------------------------------------------------------------  
  # REQUESTS THE APPROPRIATE REVIEWERS FOR THE PULL REQUEST (SIMULTANEOUSLY WITH ACCEPTANCE TESTS EXECUTION)
  # triggered by labeling RFR
  request-reviewers:
    if: github.event.action == 'ready_for_review' || (github.event.action == 'labeled' && github.event.label.name == 'RFR')  
    runs-on: ubuntu-latest

    steps:
    - name: Setup Github Actions
      uses: actions/checkout@v2
    
    - name: Install required NPM dependencies
      run: |
        npm install @actions/core 
        npm install @actions/github

    - name: Add RFR label
      if: github.event.action == 'ready_for_review'
      uses: ./.github/actions/pull_request_update/ # Uses an action in the root directory
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        addLabel: 'RFR' 
    
    - name: Request reviews
      uses: ./.github/actions/request_reviews/ # Uses an action in the root directory
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
